version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '{MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: syw5141/dnd-10th-2-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

# 볼륨 정의 (기본 설정 사용)
volumes:
  db_data: